upload all test result to job artifact

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -51,7 +51,14 @@ jobs:
             python3 CircleciScripts/run_unittest.py test_results "$currentfolder"
       - run:
           name : check unit test result 
-          command : bash CircleciScripts/check_testresult.sh test_results         
+          command : |
+            echo "sdkVersion=$sdkVersion"
+            echo "testresult=$testresult"
+            if $testresult != "0" 
+            then
+                echo "There are test failures"
+                exit 1
+            fi       
       - store_artifacts:
           path: test_results
 
